# -------------------------------------------
# Deploy to the production PyPI server
# -------------------------------------------

name: Build, test and upload to PyPI

on:
  release:
    types:
      - published

jobs:
  build:
    uses: ./.github/workflows/build_and_test.yml

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
